name: Build and test

on:
  workflow_call: {}
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-25.05

    - name: Compile
      run: |
        nix-shell --pure --run "conan profile detect"
        nix-shell --pure --run "conan build . --build=missing -s compiler.cppstd=gnu23 -s compiler.libcxx=libstdc++11"

    - name: Test
      run: |
        nix-shell --pure --run "ctest --test-dir build/Release/"
