name: Build and test

on:
  workflow_call: {}
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-25.05

    - uses: nicknovitski/nix-develop@v1
      with:
        arguments: .#native

    - name: Compile for Linux
      run: |
        conan profile detect --name default-native
        conan build --build=missing -pr:b default-native -pr:h conan/profiles/native .

    - name: Test
      run: |
        ctest --test-dir build/release-linux-clang-shared/

    - uses: nicknovitski/nix-develop@v1
      with:
        arguments: .#mingw64

    - name: Compile for Windows
      run: |
        conan profile detect --name default-mingw64
        conan build --build=missing -pr:b default-mingw64 -pr:h conan/profiles/mingw64 .
