name: Build and test

on:
  workflow_call: {}
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: nicknovitski/nix-develop@v1

    - name: Compile
      run: |
        nix develop .#native --command \
          conan build --build=missing -pr:h conan/profiles/linux .
        nix develop .#mingw64 --command \
          conan build --build=missing -pr:h conan/profiles/mingw64 .

    - name: Test
      run: |
        nix develop .#native --command \
          ctest --test-dir build/release-linux-clang-shared/
